### ISSUE TITLE
UE5.2 Support?

### ISSUE THREAD

**Issue by igorkis-scrts** [eddiebeazer/ue5-linter#3]
Hi! 
Could it be possible to support newest Unreal Engine release?

**Comment by eddiebeazer** [comment]
Hey Igor,

I’m currently not working on any unreal projects at the moment.  I’ll download 5.2 later on this week and if it doesn’t require a huge overhaul to update, I’ll post a new version

**Comment by igorkis-scrts** [comment]
@eddiebeazer 
Thanks for answer!

**Comment by eddiebeazer** [comment]
This might unfortunately need to be put on hold.  I got the plugin to compile but it looks like it doesn't show up in the context menu anymore when you right click.  I think I have to reimplement whatever method 5.2 uses now for those menus which might take a lot of time.  I added what I current have to the feature/5.2 branch.  

If I'm being honest with you, I most likely will not have the proper time to handle this until I come back to working on Unreal Engine again in the late summer. On top of that, this project is fairly dated, I planned on working on and releasing a more streamline tool for linting, testing and deploying since this is also technically not my work to share (I asked the author if I could maintain it, never got a response).  

I will at least leave this issue open in the event that I may get a little bored and want to work on it.

**Comment by kjduling** [comment]
> this is also technically not my work to share
The original license is MIT, which you should have copied over and kept when you forked it.

https://github.com/Allar/ue5-style-guide/blob/v2/LICENSE

You're allowed to make whatever changes you wish.  What you aren't allowed to do is delete the license, which it looks like you did.  oops!

**Comment by eddiebeazer** [comment]
> > this is also technically not my work to share
> 
> 
> 
> The original license is MIT, which you should have copied over and kept when you forked it.
> 
> 
> 
> https://github.com/Allar/ue5-style-guide/blob/v2/LICENSE
> 
> 
> 
> You're allowed to make whatever changes you wish.  What you aren't allowed to do is delete the license, which it looks like you did.  oops!

I was under the impression that these are 2 different projects made by the same person. That repository is for the style guide which has been updated for UE5. This repository is for the plug-in which I copied from unreal marketplace. It didn't contain any license files in it when it was copied. 

As far as I can tell, the original repo is private and not publicly available. I'd throw an MIT on here but it could be the wrong license. 

This plugin was a big huge boon for my workflow in the engine. I recently picked up some work that involves using unreal engine again, I think I just may avoid this license issue altogether by creating my own plugin

**Comment by ericmallon** [comment]
Hey @igorkis-scrts, if you were still in need of a 5.2 version of the plugin, I created a PR that includes it. 

Thankfully the needed changes weren't too bad, the main disappearing context menu bit can be solved by changing Extender->AddMenuExtension from using PathContextSourceControl to PathContextBulkOperations. 5.2 changed the context menu to not include PathContextSourceControl, so the main linter option wasn't showing up in the context menu for 5.2, changing to PathContextBulkOperations fixes that. Not sure if that is the *optimal* solution, but it seems to work!

**Comment by igorkis-scrts** [comment]
@ericmallon 
Oh, that's some great news! Thank you for updating it. 🙃
